### ISSUE TITLE
BugFix: Setting table not found when setting up with sqlite (beginner)

### ISSUE THREAD

**Issue by jugmac00** [FlaskCon/traveller#28]
When trying to set up the project with SQLite I get the following exception:

```
❯ python manage.py initialise
 x Blueprint skipped: modules.box__default.settings.view

   _____ _                             
  / ____| |                            
 | (___ | |__   ___  _ __  _   _  ___  
  \___ \| '_ \ / _ \| '_ \| | | |/ _ \ 
  ____) | | | | (_) | |_) | |_| | (_) |
 |_____/|_| |_|\___/| .__/ \__, |\___/ 
                    | |     __/ |      
                    |_|    |___/       
Copyright 2021

#######################

Cleaning...
[x] all tables dropped
[x] __pycache__ successfully deleted
[ ] unable to delete /home/jugmac00/Projects/traveller/traveller/shopyo.db: No such file or directory.
[ ] unable to delete /home/jugmac00/Projects/traveller/traveller/migrations: No such file or directory.
Auto importing models
[x] imported modules.conf.models
[x] imported modules.y.models
[x] imported modules.profile.models
[x] imported modules.schedule.models
[x] imported modules.www.models
[x] imported modules.resource.models
[x] imported modules.box__default.appadmin.models
[ ] No module named 'modules.box__default.dashboard.models'
[x] imported modules.box__default.settings.models
[ ] No module named 'modules.box__default.base.models'
[x] imported modules.box__default.auth.models
[x] imported modules.box__default.theme.models
[x] imported modules.cfp.models
Creating Db
#######################

Migrating
#######################

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'conferences'
INFO  [alembic.autogenerate.compare] Detected added table 'roles'
INFO  [alembic.autogenerate.compare] Detected added table 'settings'
INFO  [alembic.autogenerate.compare] Detected added table 'users'
INFO  [alembic.autogenerate.compare] Detected added table 'reviewer_lists'
INFO  [alembic.autogenerate.compare] Detected added table 'role_user_bridge'
INFO  [alembic.autogenerate.compare] Detected added table 'schedules'
INFO  [alembic.autogenerate.compare] Detected added table 'talks'
INFO  [alembic.autogenerate.compare] Detected added table 'author_lists'
INFO  [alembic.autogenerate.compare] Detected added table 'conf_list_user_bridge'
INFO  [alembic.autogenerate.compare] Detected added table 'days'
INFO  [alembic.autogenerate.compare] Detected added table 'score_lists'
INFO  [alembic.autogenerate.compare] Detected added table 'activities'
INFO  [alembic.autogenerate.compare] Detected added table 'talk_list_author_bridge'
INFO  [alembic.autogenerate.compare] Detected added table 'talk_list_score_bridge'
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> d2ba6fd80757, empty message
Collecting static
#######################

Uploads
#######################

Initialising Settings
#######################

Adding Dummy Settings ...
Traceback (most recent call last):
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: settings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 98, in <module>
    process()
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "manage.py", line 30, in process
    initialise()
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/shopyo/api/cmd.py", line 115, in initialise
    upload.upload()
  File "/home/jugmac00/Projects/traveller/traveller/modules/box__default/settings/upload.py", line 29, in upload
    add_setting(name, value)
  File "/home/jugmac00/Projects/traveller/traveller/modules/box__default/settings/upload.py", line 12, in add_setting
    if Settings.query.filter_by(setting=name).first():
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: settings
[SQL: SELECT settings.setting AS settings_setting, settings.value AS settings_value 
FROM settings 
WHERE settings.setting = ?
 LIMIT ? OFFSET ?]
[parameters: ('APP_NAME', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by Abdur-rahmaanJ** [comment]
Mission:

Locate the Setting table, locate the offending code and try to fix

**Comment by anushkrishnav** [comment]
Will take a look at it tonight

**Comment by IMTejesh95** [comment]
I would like to contribute to this issue. :smile:

**Comment by IMTejesh95** [comment]
I think its already been fixed?
```bash
 x Blueprint skipped: modules.box__default.settings.view

   _____ _                             
  / ____| |                            
 | (___ | |__   ___  _ __  _   _  ___  
  \___ \| '_ \ / _ \| '_ \| | | |/ _ \ 
  ____) | | | | (_) | |_) | |_| | (_) |
 |_____/|_| |_|\___/| .__/ \__, |\___/ 
                    | |     __/ |      
                    |_|    |___/       
Copyright 2021

#######################

Cleaning...
[x] all tables dropped
[x] __pycache__ successfully deleted
[ ] unable to delete /home/tejesh/contribute-on-github/traveller/traveller/shopyo.db: No such file or directory.
[x] folder '/home/tejesh/contribute-on-github/traveller/traveller/migrations' successfully deleted
Auto importing models
[x] imported modules.schedule.models
[x] imported modules.box__bizhelp.page.models
[x] imported modules.conf.models
[x] imported modules.resource.models
[x] imported modules.y.models
[x] imported modules.profile.models
[x] imported modules.www.models
[x] imported modules.box__default.theme.models
[x] imported modules.box__default.settings.models
[ ] No module named 'modules.box__default.dashboard.models'
[ ] No module named 'modules.box__default.base.models'
[x] imported modules.box__default.appadmin.models
[x] imported modules.box__default.auth.models
[x] imported modules.cfp.models
Creating Db
#######################

Migrating
#######################

INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'conferences'
INFO  [alembic.autogenerate.compare] Detected added table 'pages'
INFO  [alembic.autogenerate.compare] Detected added table 'roles'
INFO  [alembic.autogenerate.compare] Detected added table 'settings'
INFO  [alembic.autogenerate.compare] Detected added table 'users'
INFO  [alembic.autogenerate.compare] Detected added table 'reviewer_lists'
INFO  [alembic.autogenerate.compare] Detected added table 'role_user_bridge'
INFO  [alembic.autogenerate.compare] Detected added table 'schedules'
INFO  [alembic.autogenerate.compare] Detected added table 'talks'
INFO  [alembic.autogenerate.compare] Detected added table 'author_lists'
INFO  [alembic.autogenerate.compare] Detected added table 'conf_list_user_bridge'
INFO  [alembic.autogenerate.compare] Detected added table 'days'
INFO  [alembic.autogenerate.compare] Detected added table 'score_lists'
INFO  [alembic.autogenerate.compare] Detected added table 'activities'
INFO  [alembic.autogenerate.compare] Detected added table 'talk_list_author_bridge'
INFO  [alembic.autogenerate.compare] Detected added table 'talk_list_score_bridge'
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e0665d81c90b, empty message
Collecting static
#######################

Uploads
#######################

Initialising Settings
#######################

Adding Dummy Settings ...
Initialising User
#######################

Adding Admin ...
Done!
See you soon!!!
```

**Comment by Abdur-rahmaanJ** [comment]
oooh ok we close it then
