### ISSUE TITLE
BugFix: Handle login with an invalid id (beginner)

### ISSUE THREAD

**Issue by jugmac00** [FlaskCon/traveller#32]
**repro**

- try to login with invalid user account, e.g. user a@a and password a

```
Traceback (most recent call last):
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jugmac00/Projects/traveller/traveller/modules/box__default/auth/view.py", line 150, in login
    return render_template("auth/login.html", **context)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/jugmac00/Projects/traveller/traveller/modules/box__default/auth/templates/auth/login.html", line 3, in top-level template code
    {% set active_page = "login" %}
  File "/home/jugmac00/Projects/traveller/traveller/modules/box__default/base/templates/base/main_base.html", line 15, in top-level template code
    {% block content %}{% endblock %}
  File "/home/jugmac00/Projects/traveller/traveller/modules/box__default/auth/templates/auth/login.html", line 41, in block "content"
    {%include 'auth/blocks/login_form.html'%}
  File "/home/jugmac00/Projects/traveller/traveller/modules/box__default/auth/templates/auth/blocks/login_form.html", line 10, in top-level template code
    {% for error in form.user_id.errors %}
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'modules.box__default.auth.forms.LoginForm object' has no attribute 'user_id'
```

**Comment by deb17** [comment]
There is a typo in `/traveller/traveller/modules/box__default/auth/templates/auth/blocks/login_form.html`. Instead of 
```
{% for error in form.user_id.errors %}
  <li>{{ error }}</li>
{% endfor %}
```
it should be:
```
{% for error in form.email.errors %}
  <li>{{ error }}</li>
{% endfor %}
```

**Comment by Abdur-rahmaanJ** [comment]
@deb17 can you do a PR?

**Comment by deb17** [comment]
Sure.. I will let you know.

**Comment by deb17** [comment]
PR raised.
