### ISSUE TITLE
add activity breaks when adding the same text twice

### ISSUE THREAD

**Issue by jugmac00** [FlaskCon/traveller#41]
**repro**

- add activity with text "foo"
- add activity with text "foo" again

```
Traceback (most recent call last):
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jugmac00/Projects/traveller/traveller/modules/y/view.py", line 148, in schedule
    return render_template('conftheme/{}/parts/schedule.html'.format(year), **context)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/jugmac00/Projects/traveller/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/jugmac00/Projects/traveller/traveller/static/themes/front/conftheme/2021/parts/schedule.html", line 1, in top-level template code
    {% extends 'conftheme/2021/parts/base.html'%}
  File "/home/jugmac00/Projects/traveller/traveller/static/themes/front/conftheme/2021/parts/base.html", line 40, in top-level template code
    {% block body %}
  File "/home/jugmac00/Projects/traveller/traveller/static/themes/front/conftheme/2021/parts/schedule.html", line 60, in block "body"
    {% set activities = day.get_sorted_activities() %}
  File "/home/jugmac00/Projects/traveller/traveller/modules/schedule/models.py", line 25, in get_sorted_activities
    return sorted(acts,key=lambda l:l[1], reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by anushkrishnav** [comment]
On it

**Comment by iSOLveIT** [comment]
I think this issue is resolved since you can now add activity breaks with the same text twice or more and even with the same start and end time
![Screenshot from 2021-10-04 09-34-09](https://user-images.githubusercontent.com/52050586/135828359-01889115-49ec-4d30-be92-e0dbe18f4bde.png)
.
